### ISSUE TITLE
Tagging repo revisions for CD versions

### ISSUE THREAD

**Issue by robert-carroll** [ccsd/canvas-data-embulk-configs#3]
This repo provides a tag of the current CD version supported, ex _v4.2.4_
I'm evaluating the most appropriate way to retag or update the tags for this repo when _we_ make mid-version updates from our own use.

Should we trash and recreate the tag with the newest configs/commit, keeping the tag version inline with CD version, as I've been doing, or append a revision number such as _v4.2.4 r1_?

My hesitation is that _r1_ isn't something a user would see on Canvas Data Portal documentation.

**Comment by lafent** [comment]
I'm inclined to take the approach of making things make sense to someone who stumbles upon the repo and wants to jump in and use it.  If we keep any tags at levels that match Canvas, that makes it dead easy to match up.  We can always add documentation and a change log to reflect what we changed and when.  I don't really see the table definitions drifting massively, but just a few notes here and there can go a long way to making things plain and easy to understand.

**Comment by robert-carroll** [comment]
I like _dead easy_.
I've kept the same tag, with updated configs.
The recommended changelog would be an additional markdown file with a repo release date, commit, and affected CD version along with the changes applied?

**Comment by lafent** [comment]
I think that sounds sufficient.  I'm not sure what else would really be needed, but I'm not too sure how anyone else uses their CD.

**Comment by robert-carroll** [comment]
Hows this?
https://github.com/ccsd/canvas-data-embulk-configs/blob/v4.2.5/CHANGELOG.md

**Comment by lafent** [comment]
That looks great to me.  I never thought to look for a standard or recommended format.  DOH!

**Comment by robert-carroll** [comment]
Me either, I just started with a search on the topic. What settled it was that _commit diff is full of noise_.

> Using commit log diffs as changelogs is a bad idea: they're full of noise. Things like merge commits, commits with obscure titles, documentation changes, etc.
> 
> The purpose of a commit is to document a step in the evolution of the source code. Some projects clean up commits, some don't.
> 
> The purpose of a changelog entry is to document the noteworthy difference, often across multiple commits, to communicate them clearly to end users.

Thanks for the feedback!
