### ISSUE TITLE
Sneaky Ninja Release for v4.2.5

### ISSUE THREAD

**Issue by lafent** [ccsd/canvas-data-embulk-configs#5]
Apparently 4.2.5 was released without any release notes because it only updated `description` fields associated with the `requests` table (and, of course, the version number).

>  There were no changes to the data for this update which is why this was not included in the 
release notes. This update to the schema was a change to update documentation on the requests tables and users should see no changes in behavior or data. I hope this helps clarify this change. If you have any questions on this please let me know and I will be happy to help.

I did a diff of the current `schema.json` vs. a copy of my `schema.json` from v4.2.4 and the only differences are some column level `description` and the table level `description`, so it's probably about as trivial of an update as possible.

**Comment by robert-carroll** [comment]
Thanks for noticing and evaluating. I've been on the schema page all day and didn't even see the version change.

I'm going to make some changes to the README soon and I'll retag with v4.2.5

**Comment by robert-carroll** [comment]
https://github.com/ccsd/canvas-data-embulk-configs/tree/v4.2.5
